-- ----------------------------
-- Table structure for ch_social_info
-- ----------------------------
DROP TABLE IF EXISTS `ch_social_info`;
CREATE TABLE `ch_social_info`  (
  `ID` bigint(0) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '姓名',
  `CARD_NO` varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '身份证号',
  `COMP_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '单位名称',
  `WK_MODALITY_CN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '用工形式(人员类别)名称',
  `WORK_AREA_CN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '工作地域-名称',
  `POSIT_CN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '职务-名称',
  `TITLE_CN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '职称-名称',
  `HOS_BRANCH_CN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '医院支部-名称',
  `HOS_DEPART_1LEVEL_CN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '医院一级科室-名称',
  `HOS_DEPART_2LEVEL_CN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '医院二级科室-名称',
  `SOCIAL_YMONTH` varchar(20) NOT NULL COMMENT '社保年月',
  `CHANGE_TIME` varchar(20) DEFAULT NULL COMMENT '变动时间',
  `IS_EXIST_SUPPLE` int(2) default 0 NOT NULL COMMENT '是否存在补缴  0:否 1:是',
  
  #养老
  `S_PEN_BASE` decimal(10,2) DEFAULT NULL COMMENT '基数',
  `S_PEN_COMP_RATIO` decimal(10,2) DEFAULT NULL COMMENT '单位应缴比例',
  `S_PEN_COMP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位应缴金额',
  `S_PEN_COMP_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位实缴金额',
  `S_PEN_COMP_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '单位实缴差额',
  `S_PEN_COMP_OVERPAID` decimal(10,2) DEFAULT NULL COMMENT '单位多缴',
  `S_PEN_PERS_RATIO` decimal(10,2) DEFAULT NULL COMMENT '个人应缴比例',
  `S_PEN_PERS_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人应缴金额',
  `S_PEN_PERS_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人实缴金额',
  `S_PEN_PERS_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '个人实缴差额',
  `S_PEN_PERS_COMPLE` decimal(10,2) DEFAULT NULL COMMENT '个人补缴',
  
  #医疗
  `S_MEDI_BASE` decimal(10,2) DEFAULT NULL COMMENT '基数',
  `S_MEDI_COMP_RATIO` decimal(10,2) DEFAULT NULL COMMENT '单位应缴比例',
  `S_MEDI_COMP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位应缴金额',
  `S_MEDI_COMP_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位实缴金额',
  `S_MEDI_COMP_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '单位实缴差额',
  `S_MEDI_COMP_OVERPAID` decimal(10,2) DEFAULT NULL COMMENT '单位多缴',
  `S_MEDI_PERS_RATIO` decimal(10,2) DEFAULT NULL COMMENT '个人应缴比例',
  `S_MEDI_PERS_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人应缴金额',
  `S_MEDI_PERS_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人实缴金额',
  `S_MEDI_PERS_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '个人实缴差额',
  `S_MEDI_PERS_COMPLE` decimal(10,2) DEFAULT NULL COMMENT '个人补缴',
  
  #失业
  `S_UNEMP_BASE` decimal(10,2) DEFAULT NULL COMMENT '基数',
  `S_UNEMP_COMP_RATIO` decimal(10,2) DEFAULT NULL COMMENT '单位应缴比例',
  `S_UNEMP_COMP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位应缴金额',
  `S_UNEMP_COMP_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位实缴金额',
  `S_UNEMP_COMP_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '单位实缴差额',
  `S_UNEMP_COMP_OVERPAID` decimal(10,2) DEFAULT NULL COMMENT '单位多缴',
  `S_UNEMP_PERS_RATIO` decimal(10,2) DEFAULT NULL COMMENT '个人应缴比例',
  `S_UNEMP_PERS_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人应缴金额',
  `S_UNEMP_PERS_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人实缴金额',
  `S_UNEMP_PERS_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '个人实缴差额',
  `S_UNEMP_PERS_COMPLE` decimal(10,2) DEFAULT NULL COMMENT '个人补缴',
  
  #工伤
  `S_INJURY_BASE` decimal(10,2) DEFAULT NULL COMMENT '基数',
  `S_INJURY_COMP_RATIO` decimal(10,2) DEFAULT NULL COMMENT '单位应缴比例',
  `S_INJURY_COMP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位应缴金额',
  `S_INJURY_COMP_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位实缴金额',
  `S_INJURY_COMP_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '单位实缴差额',
  `S_INJURY_COMP_OVERPAID` decimal(10,2) DEFAULT NULL COMMENT '单位多缴',
  `S_INJURY_PERS_RATIO` decimal(10,2) DEFAULT NULL COMMENT '个人应缴比例',
  `S_INJURY_PERS_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人应缴金额',
  `S_INJURY_PERS_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人实缴金额',
  `S_INJURY_PERS_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '个人实缴差额',
  `S_INJURY_PERS_COMPLE` decimal(10,2) DEFAULT NULL COMMENT '个人补缴',
  
  #生育
  `S_BIRTH_BASE` decimal(10,2) DEFAULT NULL COMMENT '基数',
  `S_BIRTH_COMP_RATIO` decimal(10,2) DEFAULT NULL COMMENT '单位应缴比例',
  `S_BIRTH_COMP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位应缴金额',
  `S_BIRTH_COMP_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位实缴金额',
  `S_BIRTH_COMP_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '单位实缴差额',
  `S_BIRTH_COMP_OVERPAID` decimal(10,2) DEFAULT NULL COMMENT '单位多缴',
  `S_BIRTH_PERS_RATIO` decimal(10,2) DEFAULT NULL COMMENT '个人应缴比例',
  `S_BIRTH_PERS_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人应缴金额',
  `S_BIRTH_PERS_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人实缴金额',
  `S_BIRTH_PERS_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '个人实缴差额',
  `S_BIRTH_PERS_COMPLE` decimal(10,2) DEFAULT NULL COMMENT '个人补缴',
  
  #年金
  `S_ANNUITY_BASE` decimal(10,2) DEFAULT NULL COMMENT '基数',
  `S_ANNUITY_COMP_RATIO` decimal(10,2) DEFAULT NULL COMMENT '单位应缴比例',
  `S_ANNUITY_COMP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位应缴金额',
  `S_ANNUITY_COMP_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位实缴金额',
  `S_ANNUITY_COMP_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '单位实缴差额',
  `S_ANNUITY_COMP_OVERPAID` decimal(10,2) DEFAULT NULL COMMENT '单位多缴',
  `S_ANNUITY_PERS_RATIO` decimal(10,2) DEFAULT NULL COMMENT '个人应缴比例',
  `S_ANNUITY_PERS_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人应缴金额',
  `S_ANNUITY_PERS_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人实缴金额',
  `S_ANNUITY_PERS_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '个人实缴差额',
  `S_ANNUITY_PERS_COMPLE` decimal(10,2) DEFAULT NULL COMMENT '个人补缴',
  
  #省统筹
  `S_OVP_BASE` decimal(10,2) DEFAULT NULL COMMENT '基数',
  `S_OVP_COMP_RATIO` decimal(10,2) DEFAULT NULL COMMENT '单位应缴比例',
  `S_OVP_COMP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位应缴金额',
  `S_OVP_COMP_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位实缴金额',
  `S_OVP_COMP_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '单位实缴差额',
  `S_OVP_COMP_OVERPAID` decimal(10,2) DEFAULT NULL COMMENT '单位多缴',
  `S_OVP_PERS_RATIO` decimal(10,2) DEFAULT NULL COMMENT '个人应缴比例',
  `S_OVP_PERS_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人应缴金额',
  `S_OVP_PERS_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人实缴金额',
  `S_OVP_PERS_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '个人实缴差额',
  `S_OVP_PERS_COMPLE` decimal(10,2) DEFAULT NULL COMMENT '个人补缴',
  
  #补充医疗
  `S_SP_MEDI_BASE` decimal(10,2) DEFAULT NULL COMMENT '基数',
  `S_SP_MEDI_COMP_RATIO` decimal(10,2) DEFAULT NULL COMMENT '单位应缴比例',
  `S_SP_MEDI_COMP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位应缴金额',
  `S_SP_MEDI_COMP_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '单位实缴金额',
  `S_SP_MEDI_COMP_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '单位实缴差额',
  `S_SP_MEDI_COMP_OVERPAID` decimal(10,2) DEFAULT NULL COMMENT '单位多缴',
  `S_SP_MEDI_PERS_RATIO` decimal(10,2) DEFAULT NULL COMMENT '个人应缴比例',
  `S_SP_MEDI_PERS_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人应缴金额',
  `S_SP_MEDI_PERS_RECAP_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '个人实缴金额',
  `S_SP_MEDI_PERS_RECAP_DIFFE` decimal(10,2) DEFAULT NULL COMMENT '个人实缴差额',
  `S_SP_MEDI_PERS_COMPLE` decimal(10,2) DEFAULT NULL COMMENT '个人补缴',
  
  `REMARK4MONTH` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '月备注',
  `REMARK4YEAR` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '年备注',
  `PERS_RECAP_DIFFE_4ADDUP` decimal(10,2) DEFAULT NULL COMMENT '本年个人实缴累计差额',
  `PERS_COMPLE_DIFFE_4ADDUP` decimal(10,2) DEFAULT NULL COMMENT '本年个人补缴累计差额',
  
  `STATUS` int(0) NOT NULL DEFAULT 0 COMMENT '状态 0：正常  1：异常',
  `BTIMP_NO` varchar(25) NOT NULL COMMENT '导入编号',
  `REMARK` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备注',
  `CREATE_TIME` timestamp(0) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` timestamp(0) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `idx_CARD_NO_STATUS`(`CARD_NO`,`STATUS`) USING BTREE,
  INDEX `idx_NAME_STATUS`(`NAME`,`STATUS`) USING BTREE,
  INDEX `idx_SOCIAL_YMONTH_STATUS`(`SOCIAL_YMONTH`,`STATUS`) USING BTREE,
  INDEX `idx_IS_EXIST_SUPPLE_STATUS`(`IS_EXIST_SUPPLE`,`STATUS`) USING BTREE,
  INDEX `idx_BTIMP_NO`(`BTIMP_NO`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;


-- ----------------------------
-- Table structure for ch_social_record
-- ----------------------------
DROP TABLE IF EXISTS `ch_social_record`;
CREATE TABLE `ch_social_record`  (
  `ID` bigint(0) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `BATCH_NO` varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '批次号',
  `BATCH_USER_ACCOUNT` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '操作人账户',
  `BATCH_USER` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '操作人',
  `SUC_NUM` bigint(0) DEFAULT NULL COMMENT '成功数量',
  `FAI_NUM` bigint(0) DEFAULT NULL COMMENT '失败数量',
  `EXE_NUM` bigint(0) DEFAULT NULL COMMENT '异常数量',
  `EXIST_NUM` bigint(0) DEFAULT NULL COMMENT '已存在数量',
  `BATCH_MSG` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '批次消息',
  `STATUS` int(0) NOT NULL DEFAULT 0 COMMENT '状态 0：导入失败  1：导入成功',
  `REMARK` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备注',
  `CREATE_TIME` timestamp(0) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` timestamp(0) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `idx_STATUS`(`STATUS`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

