package com.hdfs.olo.olo_web.salary.controller;

import java.util.List;

import com.alibaba.fastjson.JSONObject;

public class PayslipExportHeadUtil {

	public static JSONObject createHead(List<String> rewards)
	{
		String head1 = 
				"{"+
				"'hTitle':'中央医院-工资单',"+
				"'heads':["+
				"{"+
				"'field':'serialNo',"+
				"'title':'序号',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':0,"+
				"'colE':0"+
				"},"+
				"{"+
				"'field':'wagesId',"+
				"'title':'人员编号',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':1,"+
				"'colE':1"+
				"},"+
				"{"+
				"'field':'name',"+
				"'title':'职工姓名',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':2,"+
				"'colE':2"+
				"},"+
				"{"+
				"'field':'cardNo',"+
				"'title':'身份证号',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':3,"+
				"'colE':3"+
				"},"+
				"{"+
				"'field':'bankCardNo',"+
				"'title':'银行卡号',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':4,"+
				"'colE':4"+
				"},"+
				"{"+
				"'field':'mobileNo',"+
				"'title':'手机号',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':5,"+
				"'colE':5"+
				"},"+
				"{"+
				"'field':'positCn',"+
				"'title':'职务',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':6,"+
				"'colE':6"+
				"},"+
				"{"+
				"'field':'titleCn',"+
				"'title':'职称',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':7,"+
				"'colE':7"+
				"},"+
				"{"+
				"'field':'hosBranchCn',"+
				"'title':'支部',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':8,"+
				"'colE':8"+
				"},"+
				"{"+
				"'field':'hosDepart1levelCn',"+
				"'title':'一级科室',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':9,"+
				"'colE':9"+
				"},"+
				"{"+
				"'field':'hosDepart2levelCn',"+
				"'title':'二级科室',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':10,"+
				"'colE':10"+
				"},"+
				"{"+
				"'field':'wkModalityCn',"+
				"'title':'人员类别',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':11,"+
				"'colE':11"+
				"},"+
				"{"+
				"'field':'departClassCn',"+
				"'title':'部门类别',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':12,"+
				"'colE':12"+
				"},"+
				"{"+
				"'field':'departClassPop',"+
				"'title':'部门类别属性',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':13,"+
				"'colE':13"+
				"},"+
				"{"+
				"'field':'stationCn',"+
				"'title':'岗位',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':14,"+
				"'colE':14"+
				"},"+
				"{"+
				"'field':'stationTypeCn',"+
				"'title':'岗位类型',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':15,"+
				"'colE':15"+
				"},"+
				"{"+
				"'field':'stationStatusCn',"+
				"'title':'岗位状态',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':16,"+
				"'colE':16"+
				"},"+
				"{"+
				"'field':'stationSeqCn',"+
				"'title':'岗位序列',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':17,"+
				"'colE':17"+
				"},"+
				"{"+
				"'field':'titleClassCn',"+
				"'title':'职称序列',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':18,"+
				"'colE':18"+
				"},"+
				"{"+
				"'field':'skillsLevelCn',"+
				"'title':'技能等级级别',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':19,"+
				"'colE':19"+
				"},"+
				"{"+
				"'field':'eduLev4nowCn',"+
				"'title':'现学历',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':20,"+
				"'colE':20"+
				"},"+
				"{"+
				"'field':'yearlySalaryMan',"+
				"'title':'年薪制人员',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':21,"+
				"'colE':21"+
				"},"+
				"{"+
				"'field':'saSumProject',"+
				"'title':'工资汇总表项目',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':22,"+
				"'colE':22"+
				"},"+
				"{"+
				"'field':'rptWkDepClass',"+
				"'title':'报工系统部门分类',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':23,"+
				"'colE':23"+
				"},"+
				"{"+
				"'field':'工数',"+
				"'title':'工数',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':24,"+
				"'colE':30,"+
				"'subs':["+
				"{"+
				"'field':'manwkStandard',"+
				"'title':'标准工数',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':24,"+
				"'colE':24"+
				"},"+
				"{"+
				"'field':'manwkAttend',"+
				"'title':'出勤工数',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':25,"+
				"'colE':25"+
				"},"+
				"{"+
				"'field':'manwkMiner',"+
				"'title':'旷工工数',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':26,"+
				"'colE':26"+
				"},"+
				"{"+
				"'field':'manwkQuit',"+
				"'title':'离职工数',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':27,"+
				"'colE':27"+
				"},"+
				"{"+
				"'field':'manwkSick',"+
				"'title':'病假工数',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':28,"+
				"'colE':28"+
				"},"+
				"{"+
				"'field':'manwkMaternity',"+
				"'title':'产假工数',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':29,"+
				"'colE':29"+
				"},"+
				"{"+
				"'field':'manwkPrivpassion',"+
				"'title':'事假工数',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':30,"+
				"'colE':30"+
				"}"+
				"]"+
				"},"+
				"{"+
				"'field':'应发工资',"+
				"'title':'应发工资',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':31,"+
				"'colE':"+(31+20+rewards.size())+","+
				"'subs':["+
				"{"+
				"'field':'wageStandard4posit',"+
				"'title':'岗位工资标准',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':31,"+
				"'colE':31"+
				"},"+
				"{"+
				"'field':'wageDay4posit',"+
				"'title':'岗位日工资',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':32,"+
				"'colE':32"+
				"},"+
				"{"+
				"'field':'岗位工资',"+
				"'title':'岗位工资',"+
				"'rowS':1,"+
				"'rowE':1,"+
				"'colS':33,"+
				"'colE':35,"+
				"'subs':["+
				"{"+
				"'field':'wageAttend',"+
				"'title':'出勤工资',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':33,"+
				"'colE':33"+
				"},"+
				"{"+
				"'field':'wageSick',"+
				"'title':'病假工资',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':34,"+
				"'colE':34"+
				"},"+
				"{"+
				"'field':'wagePositTotal',"+
				"'title':'岗位工资合计',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':35,"+
				"'colE':35"+
				"}"+
				"]"+
				"},"+
				"{"+
				"'field':'wageNightShift',"+
				"'title':'夜班费',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':36,"+
				"'colE':36"+
				"},"+
				"{"+
				"'field':'加班工资',"+
				"'title':'加班工资',"+
				"'rowS':1,"+
				"'rowE':1,"+
				"'colS':37,"+
				"'colE':38,"+
				"'subs':["+
				"{"+
				"'field':'manwkOvertime',"+
				"'title':'加班工数',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':37,"+
				"'colE':37"+
				"},"+
				"{"+
				"'field':'wageOvertime',"+
				"'title':'加班工资',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':38,"+
				"'colE':38"+
				"}"+
				"]"+
				"},"+
				"{"+
				"'field':'wageYearg',"+
				"'title':'年功工资',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':39,"+
				"'colE':39"+
				"},"+
				
				
				
				"{"+
				"'field':'津补贴',"+
				"'title':'津补贴',"+
				"'rowS':1,"+
				"'rowE':1,"+
				"'colS':40,"+
				"'colE':48,"+
				"'subs':["+
				"{"+
				"'field':'allowanceHygiene',"+
				"'title':'卫生津贴',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':40,"+
				"'colE':40"+
				"},"+
				"{"+
				"'field':'wageErrorCorrent',"+
				"'title':'纠错工资',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':41,"+
				"'colE':41"+
				"},"+
				"{"+
				"'field':'supp4tel',"+
				"'title':'电补',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':42,"+
				"'colE':42"+
				"},"+
				
				"{"+
				"'field':'supp4traffic',"+
				"'title':'交通补贴',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':43,"+
				"'colE':43"+
				"},"+
				"{"+
				"'field':'supp4mining',"+
				"'title':'下矿（井、乡）补贴',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':44,"+
				"'colE':44"+
				"},"+
				"{"+
				"'field':'supp4other',"+
				"'title':'其他补贴',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':45,"+
				"'colE':45"+
				"},"+
				"{"+
				"'field':'supp4univeStuLife',"+
				"'title':'大学生生活补贴',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':46,"+
				"'colE':46"+
				"},"+
				"{"+
				"'field':'supp4oth',"+
				"'title':'其他',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':47,"+
				"'colE':47"+
				"},"+
				"{"+
				"'field':'suppTotal',"+
				"'title':'津补贴合计',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':48,"+
				"'colE':48"+
				"}"+
				"]"+
				"},"+
			
				"{"+
				"'field':'wageTotal',"+
				"'title':'基础工资合计',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':49,"+
				"'colE':49"+
				"},"+
				"{"+
				"'field':'绩效工资',"+
				"'title':'绩效工资',"+
				"'rowS':1,"+
				"'rowE':1,"+
				"'colS':50,"+
				"'colE':"+(50+rewards.size())+","+
				"'subs':[";
		String rewItem = null;
		StringBuffer wStr = new StringBuffer();
		for(int i=0;i<rewards.size();i++)
		{
			rewItem = rewards.get(i);
			wStr.append("{");
			wStr.append("'field':'"+rewItem+"'");
			wStr.append(",");
			wStr.append("'title':'"+rewItem+"'");
			wStr.append(",");
			wStr.append("'rowS':2,");
			wStr.append("'rowE':2,");
			wStr.append("'colS':"+(50+i)+",");
			wStr.append("'colE':"+(50+i)+"");
			wStr.append("},");
		}
		
		String head2 = 
				"{"+
				"'field':'wageJxTotal',"+
				"'title':'绩效工资合计',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':"+(50+rewards.size())+","+
				"'colE':"+(50+rewards.size())+""+
				"}"+
				"]"+
				"},"+
				"{"+
				"'field':'wagePayableTotal',"+
				"'title':'应发工资合计',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':"+(51+rewards.size())+","+
				"'colE':"+(51+rewards.size())+""+
				"}"+
				"]"+
				"},"+
				"{"+
				"'field':'扣款',"+
				"'title':'扣款',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':"+(52+rewards.size())+","+
				"'colE':"+(63+rewards.size())+","+
				"'subs':["+
				"{"+
				"'field':'社会保险',"+
				"'title':'社会保险',"+
				"'rowS':1,"+
				"'rowE':1,"+
				"'colS':"+(52+rewards.size())+","+
				"'colE':"+(58+rewards.size())+","+
				"'subs':["+
				"{"+
				"'field':'bxPension',"+
				"'title':'养老保险',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':"+(52+rewards.size())+","+
				"'colE':"+(52+rewards.size())+""+
				"},"+
				"{"+
				"'field':'bxMedical',"+
				"'title':'医疗保险',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':"+(53+rewards.size())+","+
				"'colE':"+(53+rewards.size())+""+
				"},"+
				"{"+
				"'field':'bxUnemploy',"+
				"'title':'失业保险',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':"+(54+rewards.size())+","+
				"'colE':"+(54+rewards.size())+""+
				"},"+
				"{"+
				"'field':'bxSeriousIllness',"+
				"'title':'大病保险',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':"+(55+rewards.size())+","+
				"'colE':"+(55+rewards.size())+""+
				"},"+
				"{"+
				"'field':'bxHousfund',"+
				"'title':'住房公积金',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':"+(56+rewards.size())+","+
				"'colE':"+(56+rewards.size())+""+
				"},"+
				"{"+
				"'field':'bxAnnualCorpGold',"+
				"'title':'企业年金',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':"+(57+rewards.size())+","+
				"'colE':"+(57+rewards.size())+""+
				"},"+
				"{"+
				"'field':'bxTotal',"+
				"'title':'保险合计',"+
				"'rowS':2,"+
				"'rowE':2,"+
				"'colS':"+(58+rewards.size())+","+
				"'colE':"+(58+rewards.size())+""+
				"}"+
				"]"+
				"},"+
				"{"+
				"'field':'cutWater2elect',"+
				"'title':'水电费',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':"+(59+rewards.size())+","+
				"'colE':"+(59+rewards.size())+""+
				"},"+
				"{"+
				"'field':'cutHygiene',"+
				"'title':'卫生费',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':"+(60+rewards.size())+","+
				"'colE':"+(60+rewards.size())+""+
				"},"+
				"{"+
				"'field':'cutArrears',"+
				"'title':'职工欠款',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':"+(61+rewards.size())+","+
				"'colE':"+(61+rewards.size())+""+
				"},"+
				"{"+
				"'field':'cutOther',"+
				"'title':'其他扣款',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':"+(62+rewards.size())+","+
				"'colE':"+(62+rewards.size())+""+
				"},"+
				"{"+
				"'field':'cutTotal',"+
				"'title':'扣款合计',"+
				"'rowS':1,"+
				"'rowE':2,"+
				"'colS':"+(63+rewards.size())+","+
				"'colE':"+(63+rewards.size())+""+
				"}"+
				"]"+
				"},"+
				"{"+
				"'field':'taxableWage',"+
				"'title':'计税工资',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':"+(64+rewards.size())+","+
				"'colE':"+(64+rewards.size())+""+
				"},"+
				"{"+
				"'field':'taxIncomePersonal',"+
				"'title':'个税',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':"+(65+rewards.size())+","+
				"'colE':"+(65+rewards.size())+""+
				"},"+
				"{"+
				"'field':'netSalary',"+
				"'title':'实发合计',"+//20210625  由实发工资改为实发合计
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':"+(66+rewards.size())+","+
				"'colE':"+(66+rewards.size())+""+
				"},"+
				"{"+
				"'field':'netTargetYearmonth',"+
				"'title':'工资月份',"+
				"'rowS':0,"+
				"'rowE':2,"+
				"'colS':"+(67+rewards.size())+","+
				"'colE':"+(67+rewards.size())+""+
				"}"+
//				"{"+
//				"'field':'createTime',"+
//				"'title':'导入时间',"+
//				"'rowS':0,"+
//				"'rowE':2,"+
//				"'colS':"+(61+rewards.size())+","+
//				"'colE':"+(61+rewards.size())+""+
//				"}"+
				"]"+
				"}";
		return JSONObject.parseObject(head1+wStr.toString()+head2);
	}
	
	public static JSONObject createStatisticsHead(List<String> months) {
		String head1 = 
				"{"+
				"'hTitle':'中央医院-工资单统计',"+
				"'heads':["+
				"{"+
				"'field':'SERIAL_NO',"+
				"'title':'序号',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':0,"+
				"'colE':0"+
				"},"+
				"{"+
				"'field':'WK_MODALITY_CN',"+
				"'title':'人员类别',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':1,"+
				"'colE':1"+
				"},"+
				"{"+
				"'field':'DEPART_CLASS_CN',"+
				"'title':'人员部门',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':2,"+
				"'colE':2"+
				"},"+
				"{"+
				"'field':'NAME',"+
				"'title':'名称',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':3,"+
				"'colE':3"+
				"},"+
				"{"+
				"'field':'CARD_NO',"+
				"'title':'身份证号',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':4,"+
				"'colE':4"+
				"},"+
				"{"+
				"'field':'TOTAL',"+
				"'title':'统计区间工资收入',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':5,"+
				"'colE':5"+
				"},"+
				"{"+
				"'field':'MONTHS',"+
				"'title':'统计月份数',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':6,"+
				"'colE':6"+
				"},"+
				"{"+
				"'field':'AVE_VAL',"+
				"'title':'统计区间月均收入',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':7,"+
				"'colE':7"+
				"},";
		if(null == months || months.size()<=0)
			return JSONObject.parseObject(head1+"]}");
		StringBuffer supps = new StringBuffer();
		for(int i=0;i<months.size();i++)
		{
			supps.append("{");
			supps.append("'field':'"+months.get(i)+"',");
			supps.append("'title':'"+months.get(i)+"应发工资',");
			supps.append("'rowS':0,");
			supps.append("'rowE':0,");
			supps.append("'colS':"+(8+i)+",");
			supps.append("'colE':"+(8+i));
			supps.append("},");
		}
		supps.append("]}");
		return JSONObject.parseObject(head1+supps.toString());
	}
	
	public static JSONObject createStatis101Head(String year,List<String> rewards) {
		String head1 = 
				"{"+
				"'hTitle':'"+year+"全年工资明细汇总表',"+
				"'heads':["+
				"{"+
				"'field':'target_month',"+
				"'title':'月份',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':0,"+
				"'colE':0"+
				"},"+
				"{"+
				"'field':'modality',"+
				"'title':'人员类别',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':1,"+
				"'colE':1"+
				"},"+
				"{"+
				"'field':'wage_totals',"+
				"'title':'工资合计',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':2,"+
				"'colE':2"+
				"},";
				
		if(null == rewards || rewards.size()<=0)
			return JSONObject.parseObject(head1+"]}");
		StringBuffer supps = new StringBuffer();
		for(int i=0;i<rewards.size();i++)
		{
			supps.append("{");
			supps.append("'field':'"+rewards.get(i)+"',");
			supps.append("'title':'"+rewards.get(i)+"',");
			supps.append("'rowS':0,");
			supps.append("'rowE':0,");
			supps.append("'colS':"+(3+i)+",");
			supps.append("'colE':"+(3+i));
			supps.append("},");
		}
		String head2 = 
				"{"+
				"'field':'sub_total',"+
				"'title':'合计',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':"+(3+rewards.size())+","+
				"'colE':"+(3+rewards.size())+
				"}]}";
		return JSONObject.parseObject(head1+supps.toString()+head2);
	}
	
	public static JSONObject createStatis200Head(List<String> rewards) {
		String head1 = 
				"{"+
				"'hTitle':'用工类型月工资汇总表',"+
				"'heads':["+
				"{"+
				"'field':'modality',"+
				"'title':'用工形式',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':0,"+
				"'colE':0"+
				"},"+
				"{"+
				"'field':'size',"+
				"'title':'人数',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':1,"+
				"'colE':1"+
				"},"+
				"{"+
				"'field':'wage_totals',"+
				"'title':'基础工资小计',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':2,"+
				"'colE':2"+
				"},";
				
		if(null == rewards || rewards.size()<=0)
			return JSONObject.parseObject(head1+"]}");
		StringBuffer supps = new StringBuffer();
		for(int i=0;i<rewards.size();i++)
		{
			supps.append("{");
			supps.append("'field':'"+rewards.get(i)+"',");
			supps.append("'title':'"+rewards.get(i)+"',");
			supps.append("'rowS':0,");
			supps.append("'rowE':0,");
			supps.append("'colS':"+(3+i)+",");
			supps.append("'colE':"+(3+i));
			supps.append("},");
		}
		String head2 = 
				"{"+
				"'field':'reward_totals',"+
				"'title':'绩效工资合计',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':"+(3+rewards.size())+","+
				"'colE':"+(3+rewards.size())+
				"},"+
				"{"+
				"'field':'payable_totals',"+
				"'title':'应发合计',"+
				"'rowS':0,"+
				"'rowE':0,"+
				"'colS':"+(4+rewards.size())+","+
				"'colE':"+(4+rewards.size())+
				"}]}";
		return JSONObject.parseObject(head1+supps.toString()+head2);
	}
	
	public static JSONObject createStatis202Head(String ymonth) {
		String head = 
				"{"+
				"'hTitle':'工资汇总',"+
				"'heads':["+
							"{"+
							"'field':'',"+
							"'title':'"+ymonth+"工资汇总表',"+
							"'rowS':0,"+
							"'rowE':0,"+
							"'colS':0,"+
							"'colE':22,"+
							"'subs':[" +
									"{"+
								"'field':'sa_sum_project',"+
								"'title':'部门',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':0,"+
								"'colE':0"+
								"},"+
								"{"+
								"'field':'size',"+
								"'title':'人数',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':1,"+
								"'colE':1"+
								"},"+
								"{"+
								"'field':'wage_posit_totals',"+
								"'title':'岗位工资',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':2,"+
								"'colE':2"+
								"},"+
								
								"{"+
								"'field':'wage_night_shifts',"+
								"'title':'夜班费',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':3,"+
								"'colE':3"+
								"},"+
								"{"+
								"'field':'wage_overtime_totals',"+
								"'title':'加班工资',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':4,"+
								"'colE':4"+
								"},"+
								"{"+
								"'field':'wage_yearg_totals',"+
								"'title':'年功工资',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':5,"+
								"'colE':5"+
								"},"+
								"{"+
								"'field':'allowance_hygiene_totals',"+
								"'title':'卫生津贴',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':6,"+
								"'colE':6"+
								"},"+
								"{"+
								"'field':'supp_4oth_totals',"+
								"'title':'其他',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':7,"+
								"'colE':7"+
								"},"+
								"{"+
								"'field':'wage_totals',"+
								"'title':'工资小计',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':8,"+
								"'colE':8"+
								"},"+
								"{"+
								"'field':'wage_jx_totals',"+
								"'title':'绩效工资合计',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':9,"+
								"'colE':9"+
								"},"+
								"{"+
								"'field':'wage_pageable_totals',"+
								"'title':'应发合计',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':10,"+
								"'colE':10"+
								"},"+
								"{"+
								"'field':'bx_pension_totals',"+
								"'title':'养老保险',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':11,"+
								"'colE':11"+
								"},"+
								"{"+
								"'field':'bx_medical_totals',"+
								"'title':'医疗保险',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':12,"+
								"'colE':12"+
								"},"+
								"{"+
								"'field':'bx_unemp_totals',"+
								"'title':'失业保险',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':13,"+
								"'colE':13"+
								"},"+
								"{"+
								"'field':'bx_serious_totals',"+
								"'title':'大病保险',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':14,"+
								"'colE':14"+
								"},"+
								"{"+
								"'field':'bx_housfund_totals',"+
								"'title':'住房公积金',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':15,"+
								"'colE':15"+
								"},"+
								
								"{"+
								"'field':'bx_annual_totals',"+
								"'title':'企业年金',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':16,"+
								"'colE':16"+
								"},"+
								"{"+
								"'field':'bx_cut_totals',"+
								"'title':'社保扣款合计',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':17,"+
								"'colE':17"+
								"},"+
								"{"+
								"'field':'cut_other_totals',"+
								"'title':'其他扣款',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':18,"+
								"'colE':18"+
								"},"+
								"{"+
								"'field':'cut_arrears_totals',"+
								"'title':'职工欠款',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':19,"+
								"'colE':19"+
								"},"+
								"{"+
								"'field':'cut_totals',"+
								"'title':'扣款合计',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':20,"+
								"'colE':20"+
								"},"+
								"{"+
								"'field':'tax_income_totals',"+
								"'title':'个税',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':21,"+
								"'colE':21"+
								"},"+
								"{"+
								"'field':'net_salary_totals',"+
								"'title':'实发合计',"+
								"'rowS':1,"+
								"'rowE':1,"+
								"'colS':22,"+
								"'colE':22"+
								"}"+
							 "]"+
							"}"+
				"]}";
				
		return JSONObject.parseObject(head);
	}
}
